[project]
name = "kan-robustness-scaling"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "efficient-kan",
    "matplotlib>=3.10.9",
    "numpy>=2.4.4",
    "pandas>=3.0.3",
    "pykan",
    "pyyaml>=6.0.3",
    "scikit-learn>=1.8.0",
    "seaborn>=0.13.2",
    "setuptools>=81.0.0",
    "sympy>=1.14.0",
    "torch>=2.11.0",
    "tqdm>=4.67.3",
]

[tool.uv.sources]
efficient-kan = { git = "https://github.com/Blealtan/efficient-kan" }
pykan = { git = "https://github.com/KindXiaoming/pykan.git" }
